version: "3.8"

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: nitprofile_client
        restart: unless-stopped
        ports:
            - "3000:3000"
        stdin_open: true
        tty: true
        volumes:
            - ./client:/app
            - /app/node_modules
        depends_on:
            - api

    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: nitprofile_backend
        restart: unless-stopped
        env_file: ./api/.env
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
        volumes:
            - ./api:/app
            - /app/node_modules
        depends_on:
            - database

    database:
        image: postgres
        restart: always
        container_name: nitprofile_database
        ports:
            - "5432:5432"
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: yourpassword
            POSTGRES_DB: nitprofile

networks:
  default:
    name: nithub
    external: false