export * from "./config"
export * from "./errors"
export * from "./logging"
export * from "./middlewares"
export * from "./types"
export * from "./utils"
// DATABASE_NAME = nitprofile
// DATABASE_HOST = database
// DATABASE_USER = postgres
// DATABASE_PASSWORD = yourpassword
